### PR TITLE
A race to see who will do it first (1.19.4 port)

### PR DESCRIPTION
**Pull request by Hedreon**
No need for quilt port since quilt supports fabric mods (**Illegal** to do it the other way around. I tried that once and got *consequences.*)

### CODE REVIEW

**Comment by Hedreon** [comment]
Also, just to note, this PR makes your Mixin more efficient and improves compatibility with other mods, by simplifying the Mixin down to what it should've been, no unnecessary injections, just a plain and simple Mixin.

**Comment by DallenB4** [comment]
Thanks for your contributions. I appreciate the simplifying of the Mixin. This mod is designed to support as many Minecraft versions backwards as possible in one jar, and for fabric that appears to go all the way back to 1.16.5. So, changing the supported Minecraft version in `fabric.mod.json` would limit that. Also, I'm pretty sure changing the supported Java version in `fast-portals.mixins.json` and `build.gradle` would make it incompatible with 1.17.1 and earlier (or at least force players using those versions to use java 17+), but I might be wrong. If you want to change those things back, I would be happy to merge this PR.

**Comment by Hedreon** [comment]
> Thanks for your contributions. I appreciate the simplifying of the Mixin. This mod is designed to support as many Minecraft versions backwards as possible in one jar, and for fabric that appears to go all the way back to 1.16.5. So, changing the supported Minecraft version in `fabric.mod.json` would limit that. Also, I'm pretty sure changing the supported Java version in `fast-portals.mixins.json` and `build.gradle` would make it incompatible with 1.17.1 and earlier (or at least force players using those versions to use java 17+), but I might be wrong. If you want to change those things back, I would be happy to merge this PR.

Is it ok if the minimum version usable is 1.17.x?

**Comment by Hedreon** [comment]
Don't merge this yet, as I have to test it first.

**Comment by Hedreon** [comment]
Okay it works now, everything gone green, you can merge this now.

**Comment by Hedreon** [comment]
Nevermind, it still takes 4 seconds to get in and out, completely no effect, even after I changed it from a 40 to a 20

**Comment by Hedreon** [comment]
Okay so I found out the problem; I ran this mod on a fabric server and it reported an error saying that it could not find the Player Entity class that your Mixin needed.

**Comment by DallenB4** [comment]
I'm confused as to what's happening. Did you still want to merge the optimization part? I think all that needs to be changed is the code in `FastPortalsMixin.java`. For me, the mod seems to work fine on both client and server, from 1.16 to 1.19.4.

**Comment by Hedreon** [comment]
> I'm confused as to what's happening. Did you still want to merge the optimization part? I think all that needs to be changed is the code in `FastPortalsMixin.java`. For me, the mod seems to work fine on both client and server, from 1.16 to 1.19.4.

No, it's fine

**Pull request closed without merging**
